console.log('i hope everyonr is enjoying the world of js.\n do you?')
console.log('world\ttopics\t exercises')
console.log('day1\t3\t5')
console.log('day2\t3\t5')
console.log('day3\t3\t5')
console.log('day4\t3\t5')
console.log('this is a backlash symbol(\\)')
console.log('in every programming language it starts with \ "hello,World!\"')
console.log('in every programming language it starts with \ "hello,World!\"')
console.log('the saying \ seeing is believing\isnt\t correct in 2020')
